# Generated by Django 5.2.7 on 2025-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to='ads/')),
                ('title', models.CharField(blank=True, help_text='Ad description', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statue', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active')], default='pending')),
                ('media_type', models.CharField(blank=True, editable=False, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='the time when the ad starts displaying')),
                ('end_time', models.DateTimeField(help_text='the time when the ad stops displaying')),
            ],
        ),
    ]
