# Generated by Django 5.2.7 on 2025-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='boards',
            field=models.ManyToManyField(related_name='board_ads', to='boards.board'),
        ),
    ]
