# Generated by Django 5.2.7 on 2025-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='board name', max_length=100)),
                ('location', models.CharField(help_text='physical location of the board', max_length=100)),
                ('width', models.FloatField(help_text='board width in cm')),
                ('height', models.FloatField(help_text='board height in cm')),
                ('size', models.CharField(editable=False, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
